//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonPlus.Assets
{
    
    public class AssetsAssetBundleConfigs
    {
        public const string BundleName = "Assets/AssetBundle/configs";
        public const string ASSET_ASETBUNDLECONFIGCONTROLLER = "asetbundleconfigcontroller";
    }
    public class AssetsAssetBundleMulti_dependenciesAnimations
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/animations";
        public const string CONTROLLER_BUTTON = "button";
        public const string OVERRIDECONTROLLER_NEWBUTTON = "newbutton";
        public const string CONTROLLER_NEWBUTTONANIMATORCTRL = "newbuttonanimatorctrl";
    }
    public class AssetsAssetBundleMulti_dependenciesMaterials
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/materials";
        public const string MAT_MYMATERIAL = "mymaterial";
    }
    public class AssetsAssetBundleMulti_dependenciesModels
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/models";
        public const string PREFAB_GAMEOBJECT = "gameobject";
    }
    public class AssetsAssetBundleMulti_dependenciesSpritesBackgrounds
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/sprites/Backgrounds";
        public const string PNG_BACKGROUND_01 = "background_01";
        public const string PNG_BACKGROUND_02 = "background_02";
        public const string PNG_BACKGROUND_03 = "background_03";
        public const string PNG_BACKGROUND_04 = "background_04";
        public const string PNG_BACKGROUND_05 = "background_05";
        public const string PNG_BACKGROUND_06 = "background_06";
        public const string PNG_BACKGROUND_07 = "background_07";
        public const string PNG_BACKGROUND_08 = "background_08";
        public const string PNG_BACKGROUND_09 = "background_09";
        public const string PNG_BACKGROUND_10 = "background_10";
        public const string PNG_BACKGROUND_11 = "background_11";
        public const string PNG_BACKGROUND_12 = "background_12";
    }
    public class AssetsAssetBundleMulti_dependenciesSpritesButtons
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/sprites/Buttons";
        public const string PNG_ARROW_02 = "arrow_02";
        public const string PNG_ARROW_03 = "arrow_03";
        public const string PNG_ARROW_04 = "arrow_04";
        public const string PNG_ARROW_05 = "arrow_05";
        public const string PNG_ARROW_06 = "arrow_06";
        public const string PNG_ARROW_07 = "arrow_07";
        public const string PNG_BUTTON_01_LONG = "button_01_long";
        public const string PNG_BUTTON_01_MEDIUM = "button_01_medium";
        public const string PNG_BUTTON_02 = "button_02";
        public const string PNG_BUTTON_02_LONG = "button_02_long";
        public const string PNG_BUTTON_02_MEDIUM = "button_02_medium";
        public const string PNG_BUTTON_02_SMALL = "button_02_small";
        public const string PNG_BUTTON_03 = "button_03";
        public const string PNG_BUTTON_03_LONG = "button_03_long";
        public const string PNG_BUTTON_03_SMALL__2_ = "button_03_small (2)";
        public const string PNG_BUTTON_03_SMALL = "button_03_small";
        public const string PNG_BUTTON_04 = "button_04";
        public const string PNG_BUTTON_04_LONG = "button_04_long";
        public const string PNG_BUTTON_05 = "button_05";
        public const string PNG_BUTTON_06 = "button_06";
        public const string PNG_BUTTON_07 = "button_07";
        public const string PNG_BUTTON_08 = "button_08";
        public const string PNG_BUTTON_09 = "button_09";
        public const string PNG_BUTTON_10 = "button_10";
        public const string PNG_BUTTON_11 = "button_11";
        public const string PNG_BUTTON_PINK = "button_pink";
        public const string PNG_BUTTON_PINK_02 = "button_pink_02";
        public const string PNG_BUTTON_PLAY_03 = "button_play_03";
        public const string PNG_BUTTON_START_03 = "button_start_03";
    }
    public class AssetsAssetBundleMulti_dependenciesSpritesIcons
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/sprites/Icons";
        public const string PNG_ACHIVE = "achive";
        public const string PNG_ACHIVE_01 = "achive_01";
        public const string PNG_ACHIVE_02 = "achive_02";
        public const string PNG_ACHIVE_2 = "achive_2";
        public const string PNG_ARROW_BOT = "arrow_bot";
        public const string PNG_ARROW_BOT_01 = "arrow_bot_01";
        public const string PNG_ARROW_LEFT = "arrow_left";
        public const string PNG_ARROW_LEFT_01 = "arrow_left_01";
        public const string PNG_ARROW_RIGHT = "arrow_right";
        public const string PNG_ARROW_RIGHT_01 = "arrow_right_01";
        public const string PNG_ARROW_TOP = "arrow_top";
        public const string PNG_ARROW_TOP_01 = "arrow_top_01";
        public const string PNG_ARROWS = "arrows";
        public const string PNG_BUTTON_MOVE = "button_move";
        public const string PNG_BUTTON_SAVE = "button_save";
        public const string PNG_BUTTON_SHOP = "button_shop";
        public const string PNG_BUTTON_VIDEO_1 = "button_video_1";
        public const string PNG_DELETE = "delete";
        public const string PNG_EXIT = "exit";
        public const string PNG_HEART = "heart";
        public const string PNG_HEART_01 = "heart_01";
        public const string PNG_HOME_03 = "home_03";
        public const string PNG_ICON_BOOK_01 = "icon_book_01";
        public const string PNG_ICON_DAILY_BONUSES = "icon_daily_bonuses";
        public const string PNG_ICON_MAIL_1 = "icon_mail_1";
        public const string PNG_INFO_123 = "info_123";
        public const string PNG_INQURY_02 = "inqury_02";
        public const string PNG_INVITE = "invite";
        public const string PNG_LOCK = "lock";
        public const string PNG_MAIL = "mail";
        public const string PNG_MENU_02 = "menu_02";
        public const string PNG_MENU_04 = "menu_04";
        public const string PNG_MENU_05 = "menu_05";
        public const string PNG_MENU_06 = "menu_06";
        public const string PNG_MINUS = "minus";
        public const string PNG_OK = "ok";
        public const string PNG_OUT = "out";
        public const string PNG_PAUSE = "pause";
        public const string PNG_PLUS_01 = "plus_01";
        public const string PNG_RE = "re";
        public const string PNG_SETTING = "setting";
        public const string PNG_SHARE_02 = "share_02";
        public const string PNG_SHOP = "shop";
        public const string PNG_STARS_01 = "stars_01";
        public const string PNG_STARS_03 = "stars_03";
        public const string PNG_STARS_04 = "stars_04";
        public const string PNG_STATISTICS = "statistics";
        public const string PNG_STATISTICS_01 = "statistics_01";
        public const string PNG_STATISTICS_02 = "statistics_02";
        public const string PNG_TIME = "time";
        public const string PNG_VIDEO_01 = "video_01";
    }
    public class AssetsAssetBundleMulti_dependenciesSpritesPanels
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/sprites/Panels";
        public const string PNG_PANEL_02 = "panel_02";
        public const string PNG_PANEL_04 = "panel_04";
        public const string PNG_PANEL_05 = "panel_05";
        public const string PNG_PANEL_06 = "panel_06";
        public const string PNG_PANEL_07 = "panel_07";
        public const string PNG_PANEL_08 = "panel_08";
        public const string PNG_PANEL_09 = "panel_09";
        public const string PNG_PANEL_10 = "panel_10";
    }
    public class AssetsAssetBundleMulti_dependenciesSpritesParticles
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/sprites/particles";
        public const string PNG_BUTTON_LOADING = "button_loading";
        public const string PNG_BUTTON_LOADING_02 = "button_loading_02";
        public const string PNG_BUTTON_LOADING_LINE = "button_loading_line";
        public const string PNG_BUTTON_LOADING_LINE_02 = "button_loading_line_02";
        public const string PNG_FRAME = "frame";
        public const string PNG_FRAME_02 = "frame_02";
        public const string PNG_FRAME_05 = "frame_05";
        public const string PNG_FRAME_06 = "frame_06";
        public const string PNG_FRAME_07 = "frame_07";
        public const string PNG_FRAME_08 = "frame_08";
        public const string PNG_GLAZE = "glaze";
        public const string PNG_GLAZE_01 = "glaze_01";
        public const string PNG_GLOW = "glow";
        public const string PNG_GLOW_2 = "glow_2";
        public const string PNG_PARTICL_01 = "particl_01";
        public const string PNG_PARTICL_02 = "particl_02";
    }
    public class AssetsAssetBundleMulti_dependenciesTexturesBackground
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/textures/Background";
        public const string TXT_README = "readme";
        public const string PNG_SUIBOKUGA01 = "suibokuga01";
        public const string PNG_SUIBOKUGA02 = "suibokuga02";
        public const string PNG_SUIBOKUGA03 = "suibokuga03";
        public const string PNG_SUIBOKUGA04 = "suibokuga04";
        public const string PNG_SUIBOKUGA05 = "suibokuga05";
    }
    public class AssetsAssetBundleMulti_dependenciesTexturesEggs
    {
        public const string BundleName = "Assets/AssetBundle/multi_dependencies/textures/eggs";
        public const string PNG_EGG = "egg";
        public const string PNG_ICON_EGG_01 = "icon_egg_01";
        public const string PNG_ICON_EGG_04 = "icon_egg_04";
        public const string PNG_ICON_EGG_05 = "icon_egg_05";
        public const string PNG_ICON_EGG_06 = "icon_egg_06";
        public const string PNG_ICON_EGG_07 = "icon_egg_07";
        public const string PNG_ICON_EGG_08 = "icon_egg_08";
        public const string PNG_ICON_EGG_09 = "icon_egg_09";
        public const string PNG_ICON_EGG_10 = "icon_egg_10";
        public const string PNG_ICON_EGG_11 = "icon_egg_11";
        public const string PNG_ICON_EGG_12 = "icon_egg_12";
        public const string PNG_ICON_EGG_13 = "icon_egg_13";
        public const string PNG_ICON_EGG_14 = "icon_egg_14";
        public const string PNG_ICON_EGG_15 = "icon_egg_15";
        public const string PNG_ICON_EGG_16 = "icon_egg_16";
        public const string PNG_ICON_EGG_17 = "icon_egg_17";
        public const string PNG_ICON_EGG_18 = "icon_egg_18";
        public const string PNG_ICON_EGG_19 = "icon_egg_19";
        public const string PNG_ICON_EGG_20 = "icon_egg_20";
        public const string PNG_ICON_EGG_21 = "icon_egg_21";
        public const string PNG_ICON_EGG_22 = "icon_egg_22";
        public const string PNG_ICON_EGG_23 = "icon_egg_23";
        public const string PNG_ICON_EGG_24 = "icon_egg_24";
        public const string PNG_ICON_EGG_25 = "icon_egg_25";
        public const string PNG_ICON_EGG_26 = "icon_egg_26";
        public const string PNG_ICON_EGG_27 = "icon_egg_27";
        public const string PNG_ICON_EGG_28 = "icon_egg_28";
        public const string PNG_ICON_EGG_29 = "icon_egg_29";
        public const string PNG_ICON_EGG_30 = "icon_egg_30";
        public const string PNG_ICON_EGG_31 = "icon_egg_31";
        public const string PNG_ICON_EGG_32 = "icon_egg_32";
        public const string PNG_ICON_EGG_33 = "icon_egg_33";
        public const string PNG_ICON_EGG_34 = "icon_egg_34";
        public const string PNG_ICON_EGG_35 = "icon_egg_35";
        public const string PNG_ICON_EGG_36 = "icon_egg_36";
        public const string PNG_ICON_EGG_37 = "icon_egg_37";
        public const string PNG_ICON_EGG_38 = "icon_egg_38";
        public const string PNG_ICON_EGG_39 = "icon_egg_39";
        public const string PNG_ICON_EGG_40 = "icon_egg_40";
        public const string PNG_ICON_EGG_41 = "icon_egg_41";
        public const string PNG_ICON_EGG_42 = "icon_egg_42";
        public const string PNG_ICON_EGG_43 = "icon_egg_43";
        public const string PNG_ICON_EGG_44 = "icon_egg_44";
        public const string PNG_ICON_EGG_45 = "icon_egg_45";
    }
    public class AssetsAssetBundlePrefabsGame_2d
    {
        public const string BundleName = "Assets/AssetBundle/prefabs/game_2d";
        public const string PREFAB_EGG = "Egg";
        public const string PREFAB_WORLD = "World";
    }
    public class AssetsAssetBundlePrefabsGame_3d
    {
        public const string BundleName = "Assets/AssetBundle/prefabs/game_3d";
        public const string PREFAB_HIP_HOP_DANCING = "hip hop dancing";
    }
    public class AssetsAssetBundlePrefabsTemplate
    {
        public const string BundleName = "Assets/AssetBundle/prefabs/template";
        public const string PREFAB_CANVAS = "canvas";
        public const string PREFAB_PANEL_ROOT = "panel_root";
        public const string PREFAB_SCREESPACE_CAMERA_ROOT = "screespace_camera_root";
        public const string PREFAB_SCREESPACE_OVERLAY_ROOT = "screespace_overlay_root";
        public const string PREFAB_UI_ROOT = "ui_root";
        public const string PREFAB_WORLDSPACE_ROOT = "worldspace_root";
    }
    public class AssetsAssetBundlePrefabsUiPanel
    {
        public const string BundleName = "Assets/AssetBundle/prefabs/ui/panel";
        public const string PREFAB_PANEL = "Panel";
    }
    public class AssetsAssetBundleSprite_atlasHd
    {
        public const string BundleName = "Assets/AssetBundle/sprite_atlas/hd";
        public const string SPRITEATLAS_COMMONBOX = "commonbox";
    }
    public class AssetsAssetBundleSprite_atlasSd
    {
        public const string BundleName = "Assets/AssetBundle/sprite_atlas/sd";
        public const string SPRITEATLAS_COMMONBOX = "commonbox";
    }
    public class AssetsAssetBundleTexturesBackground
    {
        public const string BundleName = "Assets/AssetBundle/textures/background";
        public const string PNG_FUBEN1 = "fuben1";
        public const string PNG_FUBEN2 = "fuben2";
        public const string PNG_FUBEN3 = "fuben3";
        public const string PNG_LOGONBG = "logonbg";
        public const string JPG_MAINBG = "mainbg";
        public const string PNG_SELECTHERO = "selecthero";
        public const string PNG_SELECTLEVEL2 = "selectlevel2";
    }
    public class AssetsAssetBundleTexturesNpc
    {
        public const string BundleName = "Assets/AssetBundle/textures/npc";
        public const string PNG_CUNZHANG = "cunzhang";
        public const string PNG_DAFASHI = "dafashi";
        public const string PNG_GUANKA = "guanka";
        public const string PNG_LENSHENTUOER = "lenshentuoer";
        public const string PNG_YADIANNA = "yadianna";
        public const string PNG_YASEWANG = "yasewang";
        public const string PNG_ZHITIANSHI = "zhitianshi";
    }
    public class AssetsAssetBundleTexturesPackages
    {
        public const string BundleName = "Assets/AssetBundle/textures/packages";
        public const string PNG_CHONGWUJINGPO = "chongwujingpo";
        public const string PNG_COPPER_BOX = "copper_box";
        public const string PNG_GEM3LV1 = "gem3lv1";
        public const string PNG_GEM4LV2 = "gem4lv2";
        public const string PNG_GEM6LV3 = "gem6lv3";
        public const string PNG_STRENGSTONE = "strengstone";
        public const string PNG_VCLOTHES = "vclothes";
        public const string PNG_VCLOTHES3 = "vclothes3";
        public const string PNG_VPANTS = "vpants";
        public const string PNG_VRING2 = "vring2";
        public const string PNG_VSHOES = "vshoes";
        public const string PNG_VSTAFF = "vstaff";
        public const string PNG_VSTAFF1 = "vstaff1";
    }
    public class AssetsAssetBundleTexturesUi
    {
        public const string BundleName = "Assets/AssetBundle/textures/ui";
        public const string PNG_COMMONATLAS = "commonatlas";
        public const string PNG_CREATEROLEATLAS = "createroleatlas";
        public const string PNG_MAINATLAS = "mainatlas";
        public const string PNG_MMAP = "mmap";
        public const string PNG_UI_ATLAS_BATTLE = "ui_atlas_battle";
        public const string PNG_UI_ATLAS_ICON_COMMON = "ui_atlas_icon_common";
        public const string PNG_UI_ATLAS_IMG_LOCAL_NORMAL = "ui_atlas_img_local_normal";
    }
}
